### ISSUE TITLE
Not working with latest Nuxt 3.0.0 rc14

### ISSUE THREAD

**Issue by finnbuster** [nuxt-community/google-fonts-module#113]
When I install the module and add to modules in defineNuxtConfig I'm getting:

 ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')                                                               14:21:55

  at nuxtModule (node_modules/@nuxtjs/google-fonts/dist/module.js:32:21)
  at installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1853:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)

**Comment by finnbuster** [comment]
Fixed by using https://github.com/nuxt-community/google-fonts-module/issues/107
