### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'options') 

### ISSUE THREAD

**Issue by shareefhadid** [nuxt-community/google-fonts-module#116]
I followed the setup instructions here: https://google-fonts.nuxtjs.org/setup

But these seem to be out of date (or maybe this plugin is). It is unable to compile, please see the stack trace below:
```
Cannot start nuxt:  Cannot read properties of undefined (reading 'options') 

  at nuxtModule (node_modules\@nuxtjs\google-fonts\dist\module.js:32:21)
  at installModule (/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by mobdiz** [comment]
Also ran into this problem today. Installing the pre-release version helped. @nuxtjs/google-fonts@prerelease

**Comment by kuohuanhuan** [comment]
Using the prerelease version for Nuxt 3 will help.

<https://www.npmjs.com/package/@nuxtjs/google-fonts/v/3.0.0-1?activeTab=versions>

**Comment by gustojs** [comment]
It would be nice to have this at least included in the readme, if not the docs.

**Comment by ricardogobbosouza** [comment]
I will update the documentation and release v3 soon
