### ISSUE TITLE
Cannot read properties of undefined (reading 'link')

### ISSUE THREAD

**Issue by joshwcorbett** [nuxt-community/google-fonts-module#117]
Project Info:
```bash
.../Library/pnpm/store/v3/tmp/dlx-26945  |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-26945  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Nuxi 3.0.0                                                                                                       14:37:40
                                                                                                                 14:37:40
RootDir: /Users/josh/Repositories/fnf-store                                                                      14:37:40
Nuxt project info: (copied to clipboard)                                                                         14:37:40

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.5.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.21.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `plausible`, `storyblok`, `apollo`, `googleFonts`, `vite`, `build`, `devServerHandlers`
- Runtime Modules:  `@vueuse/nuxt@9.4.0`, `nuxt-icon@0.1.7`, `@storyblok/nuxt@4.6.0`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/apollo@5.0.0-alpha.2`, `@nuxtjs/plausible@0.2.0`, `@nuxtjs/google-fonts@2.0.0`
- Build Modules:    `-`
------------------------------
```
Nuxt Config:
```ts
  modules: [
    '@nuxtjs/google-fonts',
  ],
  // Google Fonts Configuration
  googleFonts: {
    families: {
      Archivo: true,
    },
  },
```

Console error:
```bash
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'link')                                 14:36:36

  at node_modules/.pnpm/@nuxtjs+google-fonts@2.0.0/node_modules/@nuxtjs/google-fonts/dist/module.js:48:44
  at node_modules/.pnpm/hookable@5.4.1/node_modules/hookable/dist/index.mjs:39:70
  at async build (node_modules/.pnpm/nuxt@3.0.0-rc.13_jbw4qtqtinc3kuqpq2aa3cjwz4/node_modules/nuxt/dist/index.mjs:2198:3)
  at async Promise.all (index 1)
  at async load (node_modules/.pnpm/nuxi@3.0.0-rc.13/node_modules/nuxi/dist/chunks/dev.mjs:6785:9)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.0.0-rc.13/node_modules/nuxi/dist/chunks/dev.mjs:6839:5)
  at async _main (node_modules/.pnpm/nuxi@3.0.0-rc.13/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by aleavikraman** [comment]
have you tried updated to the pre-release version? `npm install --save-dev @nuxtjs/google-fonts@prerelease`

**Comment by liambroadbent** [comment]
I was having a similar issue, 

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')      
 
 I updated the to the preinstall as detailed above and its working, the error is gone. 
 
 I do still have  WARN  No provided fonts. but ill look into that. 
 
Thanks @aleavikraman

**Comment by abdurrahmanseyidoglu** [comment]
> have you tried updated to the pre-release version? `npm install --save-dev @nuxtjs/google-fonts@prerelease`

This has worked for me

**Comment by dosstx** [comment]
Thanks, adding that module version works for me.

**Comment by ricardogobbosouza** [comment]
I will update the documentation and release v3 soon
